travis:
  secure:
    BINSTAR_TOKEN: Whv4GaMjpsaXRBLvwzy4M9V7lqy4vBqyHnqFJzHx0HXkuUxO7lTCCtI9CMx/sGgp62zLwD4w8UYc/L8tZaJpnhEf4CkJVXGoNQHCGs1pdmP8/tgBTt3sXQeLk/pzTFBei8fBj5pK8ZEOfM1snoFmjji6vi9nKGidNLYOW8VAHFkuq3hzd2jUGhmOXG6WIig4ww318kDBS8lvv+GqO1sXJzVBfJ5WIYlBvuWThWhSev8L0s5zJeLRJq5mmQL8urxVNkENAVv/lhIomslzoZ4SqkNI/HpO+pSUPULENHsGeEXrIu4U7CQ+YFTjfQYs19K96Pq30mqGYXbQ2mosXFILXikG6a/aymO/miaPaDtF5jO5uQRih44ZIzli+gyuojetyJXMCtdKOthjs3hqkD4cno56xLa5fn7bLYlCZM9+XAxnbIXlv9lP+p4rTCY6/a4CvSCnQB4/xJUIHXM1+NGWHcjHateoWRhrf3+vUUup9+Tj9mCy4GSFi4s+7RjykGCqtQ1eeIRMfhd41oB4xDaJEYgNcY96CUgX0SEHCyuu3CmzJwqO9u3AjM7hUNeCjC7S3oCc+8spcmS2cbGN4J+xC42u0UatrqXqNZTPfByLztWzcAtJW9g5r/StNtZY57pOAKhXyzA/L6FJSHol6Gxfbgih+DhTX36V/DaDI9xBODU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
